name: allTheBasics
version: '${project.version}'
main: com.sieadev.allthebasics.AllTheBasics
api-version: 1.20
author: sieadev
description: All the basics your minecraft Server needs
permissions:
  atb:
    children:
      gamemode:
        children:
          creative:
            description: use /gm creative
          spectator:
            description: use /gm spectator
          survival:
            description: use /gm survival
          adventure:
            description: use /gm adventure
      chat:
        children:
          color:
            description: use colorful text in text
          highlightNumbers:
            description: auto-highlight numbers
          math:
            description: auto-calculate math
          emoji:
            description: auto-convert emojis
      fakeop:
        description: use /fakeop
      heal:
        description: use /healPlayer
      feed:
        description: use /feed
      fly:
        description: use /fly
      freeze:
        description: use /freeze
      teleport:
        description: use /tp
      vanish:
        description: use /vanish
      disguise:
        description:  use /disguise
      timer:
        children:
            start:
              descrption: use /timer start
            stop:
              descrption: use /timer stop
      burn:
        description: use /burn
      suicide:
        description: use /suicide
      kickall:
        description: use /kickall
      kickplayer:
        description: use /kickplayer
      tpall:
        description: use /tpall
      home:
        children:
          set:
            descrption: use /sethome
          find:
            description: use /findhome
          teleport:
            description: use /home
      setitemname:
        description: use /setitemname
      playtime:
        description: use /playtime
      blind:
        description: use /blind
      directmessage:
        description: use /dm
      ignore:
        description: use /ignore
      flyspeed:
        description: use /flyspeed

commands:
  heal:
    permission: atb.heal
    usage: §c/heal <player>
    description: Heal a player
    aliases: h
  feed:
    permission: atb.feed
    usage: §c/feed <player>
    description: Feed a player
    aliases: f
  fakeop:
    permission: atb.fakeop
    usage: §c/fakeop <player>
    description: Give a player fake OP
  timer:
    permission: atb.timer
    usage: §c/timer <start/stop>
    description: Starts or stops a personal timer for a player
  freeze:
    permission: atb.freeze
    usage: §c/freeze <target>
    description: Freeze a player
  fly:
    permission: atb.fly
    usage: §c/fly
    description: Enables flying
  disguise:
    permission: atb.disguise
    usage: §c/disguise
    description: Disguise as a player
  vanish:
    permission: atb.vanish
    usage: §c/vanish
    description: Become invisible
  tp:
    permission: atb.teleport
    usage: §c/teleport <player>
    description: Teleport to a player // Teleport a player to a player
    aliases: teleport
  gm:
    permissions: [atb.gamemode.creative, atb.gamemode.survival, atb.gamemode.adventure, atb.gamemode.spectator]
    usage: §c/gm <gamemode>
    description: Change your Gamemmode
    aliases: gamemode
  gm0:
    permission: atb.gamemode.survival
    usage: §c/gm1
    description: Change your Gamemode to survival
    aliases: survival
  gm1:
    permission: atb.gamemode.creative
    usage: §c/gm1
    description: Change your Gamemode to creative
    aliases: creative
  gm2:
    permission: atb.gamemode.adventure
    usage: §c/gm1
    description: Change your Gamemode to adventure
    aliases: adventure
  gm3:
    permission: atb.gamemode.spectator
    usage: §c/gm1
    description: Change your Gamemode to spectator
    aliases: spectator
  burn:
    permission: atb.burn
    usage: §c/burn <player>
    description: Light a Player on fire
  suicide:
    permission: atb.suicide
    usage: §c/suicide
    description: Kill yourself
  kickall:
    permission: atb.kickall
    usage: §c/kickall
    description: Kick all Players
  tpall:
    permission: atb.tpall
    usage: §c/tpall
    description: Tp all players to your location
  home:
    permissions: [atb.home.teleport, atb.home.find]
    usage: §c/home
    description: Teleport home
  findhome:
    permission: atb.home.find
    usage: §c/findhome
    description: Find your home
  sethome:
    permission: atb.home.set
    usage: §c/sethome
    description: Set your home
  playtime:
    permission: atb.playtime
    usage: §c/playtime
    description: Get your playtime
  setitemname:
    permission: atb.setitemname
    usage: §c/setitemname <name>
    description: Set a new Item name
  blind:
    permission: atb.blind
    usage: §c/blind <player>
    description: Blind someone
  dm:
    permission: atb.directmessage
    usage: §c/dm <player> <message>
    description: Send a direct message to a player
    aliases: [directmessage, pm, msg]
  block:
    permission: atb.ignore
    usage: §c/block <player>
    aliases: ignore
  repair:
    permission: atb.repair
    usage: §c/repair
    description: Repair an item
  flyspeed:
    permission: atb.flyspeed
    usage: §c/flyspeed <player> <l>
    description: set your flyspeed